/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockOracleSol from "./MockOracle.sol";
export type { mockOracleSol };
import type * as policySol from "./Policy.sol";
export type { policySol };
export type { ParametricInsurance } from "./ParametricInsurance";
export type { Treasury } from "./Treasury";
