/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ParametricInsuranceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "coverageAmountOf"
      | "owner"
      | "purchasePolicy"
      | "renounceOwnership"
      | "totalPremiums"
      | "transferOwnership"
      | "triggerPayout"
      | "withdrawSurplus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PayoutTriggered"
      | "PolicyPurchased"
      | "SurplusWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "coverageAmountOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchasePolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPremiums",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerPayout",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSurplus",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "coverageAmountOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchasePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPremiums",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSurplus",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutTriggeredEvent {
  export type InputTuple = [
    eventId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    eventId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPurchasedEvent {
  export type InputTuple = [
    purchaser: AddressLike,
    premium: BigNumberish,
    coverageUnits: BigNumberish
  ];
  export type OutputTuple = [
    purchaser: string,
    premium: bigint,
    coverageUnits: bigint
  ];
  export interface OutputObject {
    purchaser: string;
    premium: bigint;
    coverageUnits: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurplusWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ParametricInsurance extends BaseContract {
  connect(runner?: ContractRunner | null): ParametricInsurance;
  waitForDeployment(): Promise<this>;

  interface: ParametricInsuranceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  coverageAmountOf: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  purchasePolicy: TypedContractMethod<[], [void], "payable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalPremiums: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerPayout: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, eventId: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawSurplus: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "coverageAmountOf"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchasePolicy"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPremiums"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerPayout"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, eventId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawSurplus"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutTriggered"
  ): TypedContractEvent<
    PayoutTriggeredEvent.InputTuple,
    PayoutTriggeredEvent.OutputTuple,
    PayoutTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPurchased"
  ): TypedContractEvent<
    PolicyPurchasedEvent.InputTuple,
    PolicyPurchasedEvent.OutputTuple,
    PolicyPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "SurplusWithdrawn"
  ): TypedContractEvent<
    SurplusWithdrawnEvent.InputTuple,
    SurplusWithdrawnEvent.OutputTuple,
    SurplusWithdrawnEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutTriggered(bytes32,address,uint256)": TypedContractEvent<
      PayoutTriggeredEvent.InputTuple,
      PayoutTriggeredEvent.OutputTuple,
      PayoutTriggeredEvent.OutputObject
    >;
    PayoutTriggered: TypedContractEvent<
      PayoutTriggeredEvent.InputTuple,
      PayoutTriggeredEvent.OutputTuple,
      PayoutTriggeredEvent.OutputObject
    >;

    "PolicyPurchased(address,uint256,uint256)": TypedContractEvent<
      PolicyPurchasedEvent.InputTuple,
      PolicyPurchasedEvent.OutputTuple,
      PolicyPurchasedEvent.OutputObject
    >;
    PolicyPurchased: TypedContractEvent<
      PolicyPurchasedEvent.InputTuple,
      PolicyPurchasedEvent.OutputTuple,
      PolicyPurchasedEvent.OutputObject
    >;

    "SurplusWithdrawn(address,uint256)": TypedContractEvent<
      SurplusWithdrawnEvent.InputTuple,
      SurplusWithdrawnEvent.OutputTuple,
      SurplusWithdrawnEvent.OutputObject
    >;
    SurplusWithdrawn: TypedContractEvent<
      SurplusWithdrawnEvent.InputTuple,
      SurplusWithdrawnEvent.OutputTuple,
      SurplusWithdrawnEvent.OutputObject
    >;
  };
}
