/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Policy {
  export type PolicyStruct = {
    id: BigNumberish;
    policyholder: AddressLike;
    premium: BigNumberish;
    payout: BigNumberish;
    threshold: BigNumberish;
    active: boolean;
    triggered: boolean;
  };

  export type PolicyStructOutput = [
    id: bigint,
    policyholder: string,
    premium: bigint,
    payout: bigint,
    threshold: bigint,
    active: boolean,
    triggered: boolean
  ] & {
    id: bigint;
    policyholder: string;
    premium: bigint;
    payout: bigint;
    threshold: bigint;
    active: boolean;
    triggered: boolean;
  };
}

export interface PolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyPolicy"
      | "getPoliciesByUser"
      | "nextPolicyId"
      | "owner"
      | "policies"
      | "renounceOwnership"
      | "totalFunds"
      | "transferOwnership"
      | "triggerPolicy"
      | "userPolicyIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PayoutExecuted"
      | "PolicyPurchased"
      | "PolicyTriggered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyPolicy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoliciesByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPolicyId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPolicyIds",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoliciesByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPolicyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPolicyIds",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutExecutedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [policyId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    policyId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPurchasedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    policyholder: AddressLike,
    premium: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    policyholder: string,
    premium: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    policyholder: string;
    premium: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyTriggeredEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Policy extends BaseContract {
  connect(runner?: ContractRunner | null): Policy;
  waitForDeployment(): Promise<this>;

  interface: PolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyPolicy: TypedContractMethod<
    [payout: BigNumberish, threshold: BigNumberish],
    [void],
    "payable"
  >;

  getPoliciesByUser: TypedContractMethod<
    [user: AddressLike],
    [Policy.PolicyStructOutput[]],
    "view"
  >;

  nextPolicyId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        policyholder: string;
        premium: bigint;
        payout: bigint;
        threshold: bigint;
        active: boolean;
        triggered: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalFunds: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userPolicyIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyPolicy"
  ): TypedContractMethod<
    [payout: BigNumberish, threshold: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getPoliciesByUser"
  ): TypedContractMethod<
    [user: AddressLike],
    [Policy.PolicyStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextPolicyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        policyholder: string;
        premium: bigint;
        payout: bigint;
        threshold: bigint;
        active: boolean;
        triggered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFunds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerPolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPolicyIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutExecuted"
  ): TypedContractEvent<
    PayoutExecutedEvent.InputTuple,
    PayoutExecutedEvent.OutputTuple,
    PayoutExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPurchased"
  ): TypedContractEvent<
    PolicyPurchasedEvent.InputTuple,
    PolicyPurchasedEvent.OutputTuple,
    PolicyPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyTriggered"
  ): TypedContractEvent<
    PolicyTriggeredEvent.InputTuple,
    PolicyTriggeredEvent.OutputTuple,
    PolicyTriggeredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutExecuted(uint256,address,uint256)": TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;
    PayoutExecuted: TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;

    "PolicyPurchased(uint256,address,uint256,uint256)": TypedContractEvent<
      PolicyPurchasedEvent.InputTuple,
      PolicyPurchasedEvent.OutputTuple,
      PolicyPurchasedEvent.OutputObject
    >;
    PolicyPurchased: TypedContractEvent<
      PolicyPurchasedEvent.InputTuple,
      PolicyPurchasedEvent.OutputTuple,
      PolicyPurchasedEvent.OutputObject
    >;

    "PolicyTriggered(uint256)": TypedContractEvent<
      PolicyTriggeredEvent.InputTuple,
      PolicyTriggeredEvent.OutputTuple,
      PolicyTriggeredEvent.OutputObject
    >;
    PolicyTriggered: TypedContractEvent<
      PolicyTriggeredEvent.InputTuple,
      PolicyTriggeredEvent.OutputTuple,
      PolicyTriggeredEvent.OutputObject
    >;
  };
}
