/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITreasury__factory } from "./ITreasury__factory";
export { Policy__factory } from "./Policy__factory";
