/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockOracleSol from "./MockOracle.sol";
export * as policySol from "./Policy.sol";
export { ParametricInsurance__factory } from "./ParametricInsurance__factory";
export { Treasury__factory } from "./Treasury__factory";
