/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPolicy__factory } from "./IPolicy__factory";
export { MockOracle__factory } from "./MockOracle__factory";
