/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicy,
  IPolicyInterface,
} from "../../../contracts/MockOracle.sol/IPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "policyId",
        type: "uint256",
      },
    ],
    name: "triggerPolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyInterface {
    return new Interface(_abi) as IPolicyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPolicy {
    return new Contract(address, _abi, runner) as unknown as IPolicy;
  }
}
