/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Policy {
  export type PolicyDataStruct = {
    id: BigNumberish;
    policyholder: AddressLike;
    premium: BigNumberish;
    payout: BigNumberish;
    threshold: BigNumberish;
    active: boolean;
    triggered: boolean;
  };

  export type PolicyDataStructOutput = [
    id: bigint,
    policyholder: string,
    premium: bigint,
    payout: bigint,
    threshold: bigint,
    active: boolean,
    triggered: boolean
  ] & {
    id: bigint;
    policyholder: string;
    premium: bigint;
    payout: bigint;
    threshold: bigint;
    active: boolean;
    triggered: boolean;
  };
}

export interface PolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyPolicy"
      | "fulfill"
      | "getPoliciesByUser"
      | "maxPayout"
      | "nextPolicyId"
      | "oracle"
      | "owner"
      | "pause"
      | "paused"
      | "payoutExecuted"
      | "policies"
      | "renounceOwnership"
      | "requestToPolicy"
      | "requestTriggerCheck"
      | "setMaxPayout"
      | "setOracle"
      | "terminatePolicy"
      | "transferOwnership"
      | "treasury"
      | "triggerPolicy"
      | "unpause"
      | "userPolicyIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OracleFulfilled"
      | "OracleRequested"
      | "OwnershipTransferred"
      | "Paused"
      | "PayoutExecuted"
      | "PolicyCancelled"
      | "PolicyPurchased"
      | "PolicyTriggered"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyPolicy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfill",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoliciesByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "maxPayout", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextPolicyId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutExecuted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestToPolicy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTriggerCheck",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "terminatePolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "triggerPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPolicyIds",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fulfill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoliciesByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxPayout", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextPolicyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payoutExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestToPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTriggerCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "terminatePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "triggerPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userPolicyIds",
    data: BytesLike
  ): Result;
}

export namespace OracleFulfilledEvent {
  export type InputTuple = [requestId: BytesLike, value: BigNumberish];
  export type OutputTuple = [requestId: string, value: bigint];
  export interface OutputObject {
    requestId: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRequestedEvent {
  export type InputTuple = [policyId: BigNumberish, requestId: BytesLike];
  export type OutputTuple = [policyId: bigint, requestId: string];
  export interface OutputObject {
    policyId: bigint;
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutExecutedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [policyId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    policyId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCancelledEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPurchasedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    policyholder: AddressLike,
    premium: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    policyholder: string,
    premium: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    policyholder: string;
    premium: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyTriggeredEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Policy extends BaseContract {
  connect(runner?: ContractRunner | null): Policy;
  waitForDeployment(): Promise<this>;

  interface: PolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyPolicy: TypedContractMethod<
    [payout: BigNumberish, threshold: BigNumberish],
    [void],
    "payable"
  >;

  fulfill: TypedContractMethod<
    [requestId: BytesLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPoliciesByUser: TypedContractMethod<
    [user: AddressLike],
    [Policy.PolicyDataStructOutput[]],
    "view"
  >;

  maxPayout: TypedContractMethod<[], [bigint], "view">;

  nextPolicyId: TypedContractMethod<[], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payoutExecuted: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        policyholder: string;
        premium: bigint;
        payout: bigint;
        threshold: bigint;
        active: boolean;
        triggered: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestToPolicy: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  requestTriggerCheck: TypedContractMethod<
    [policyId: BigNumberish],
    [string],
    "nonpayable"
  >;

  setMaxPayout: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<
    [oracleAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  terminatePolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  triggerPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userPolicyIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyPolicy"
  ): TypedContractMethod<
    [payout: BigNumberish, threshold: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fulfill"
  ): TypedContractMethod<
    [requestId: BytesLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPoliciesByUser"
  ): TypedContractMethod<
    [user: AddressLike],
    [Policy.PolicyDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxPayout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextPolicyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payoutExecuted"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        policyholder: string;
        premium: bigint;
        payout: bigint;
        threshold: bigint;
        active: boolean;
        triggered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestToPolicy"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestTriggerCheck"
  ): TypedContractMethod<[policyId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxPayout"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[oracleAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "terminatePolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "triggerPolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPolicyIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OracleFulfilled"
  ): TypedContractEvent<
    OracleFulfilledEvent.InputTuple,
    OracleFulfilledEvent.OutputTuple,
    OracleFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "OracleRequested"
  ): TypedContractEvent<
    OracleRequestedEvent.InputTuple,
    OracleRequestedEvent.OutputTuple,
    OracleRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutExecuted"
  ): TypedContractEvent<
    PayoutExecutedEvent.InputTuple,
    PayoutExecutedEvent.OutputTuple,
    PayoutExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCancelled"
  ): TypedContractEvent<
    PolicyCancelledEvent.InputTuple,
    PolicyCancelledEvent.OutputTuple,
    PolicyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPurchased"
  ): TypedContractEvent<
    PolicyPurchasedEvent.InputTuple,
    PolicyPurchasedEvent.OutputTuple,
    PolicyPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyTriggered"
  ): TypedContractEvent<
    PolicyTriggeredEvent.InputTuple,
    PolicyTriggeredEvent.OutputTuple,
    PolicyTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OracleFulfilled(bytes32,uint256)": TypedContractEvent<
      OracleFulfilledEvent.InputTuple,
      OracleFulfilledEvent.OutputTuple,
      OracleFulfilledEvent.OutputObject
    >;
    OracleFulfilled: TypedContractEvent<
      OracleFulfilledEvent.InputTuple,
      OracleFulfilledEvent.OutputTuple,
      OracleFulfilledEvent.OutputObject
    >;

    "OracleRequested(uint256,bytes32)": TypedContractEvent<
      OracleRequestedEvent.InputTuple,
      OracleRequestedEvent.OutputTuple,
      OracleRequestedEvent.OutputObject
    >;
    OracleRequested: TypedContractEvent<
      OracleRequestedEvent.InputTuple,
      OracleRequestedEvent.OutputTuple,
      OracleRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PayoutExecuted(uint256,address,uint256)": TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;
    PayoutExecuted: TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;

    "PolicyCancelled(uint256)": TypedContractEvent<
      PolicyCancelledEvent.InputTuple,
      PolicyCancelledEvent.OutputTuple,
      PolicyCancelledEvent.OutputObject
    >;
    PolicyCancelled: TypedContractEvent<
      PolicyCancelledEvent.InputTuple,
      PolicyCancelledEvent.OutputTuple,
      PolicyCancelledEvent.OutputObject
    >;

    "PolicyPurchased(uint256,address,uint256,uint256)": TypedContractEvent<
      PolicyPurchasedEvent.InputTuple,
      PolicyPurchasedEvent.OutputTuple,
      PolicyPurchasedEvent.OutputObject
    >;
    PolicyPurchased: TypedContractEvent<
      PolicyPurchasedEvent.InputTuple,
      PolicyPurchasedEvent.OutputTuple,
      PolicyPurchasedEvent.OutputObject
    >;

    "PolicyTriggered(uint256)": TypedContractEvent<
      PolicyTriggeredEvent.InputTuple,
      PolicyTriggeredEvent.OutputTuple,
      PolicyTriggeredEvent.OutputObject
    >;
    PolicyTriggered: TypedContractEvent<
      PolicyTriggeredEvent.InputTuple,
      PolicyTriggeredEvent.OutputTuple,
      PolicyTriggeredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
